[doku]
name = "B450"
beschreibung = '''
Dies ist eine kurze Beschreibung
         mit Zeilenumbrüchen
und Sonderzeichen'''
anmerkung = """
irgendwas kurzes

mit Zeilenumbrüchen
    und einzügen
"""
entladedatum = '2015-08-04'

[version]
aktuell = 1.7
produktiv = 1.5
